### ISSUE TITLE
dependency management

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/wipac-dev-tools#15]
General issue here; it applies to multiple repos.

Recently I took a look at the virtualenv size, and it was >300MB.  Let's try to trim that down.

1. Handle dev-only dependencies, for testing, separately.
  Make a `requirements-dev.txt` file and put those dependencies there. Automated tests and local development can then install from `requirements-dev.txt`, while prod uses the regular `requirements.txt`.

```
-r requirements.txt
pytest
mypy
```

2. Make optional features for optional dependencies.
  Here I'm thinking things like `flask` or `grpc` telemetry support.  A client will need to know when it will use a feature, but hopefully that's mostly us, so not a problem.
  https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies

**Comment by ric-evans** [comment]
https://github.com/WIPACrepo/rest-tools and https://github.com/WIPACrepo/mou-dashboard now have `requirements-dev.txt`

These contain testing and typing packages.

**Comment by ric-evans** [comment]
I'm going to close this. The first part is satisfied and the second part doesn't really apply to _this_ repo. It will be applicable in others.
