### ISSUE TITLE
Prep + Publish to PyPI

### ISSUE THREAD

**Issue by ric-evans** [WIPACrepo/wipac-dev-tools#20]
`wipac-dev-tools` is our guinea pig. It also has no requirements which will make this transition less painful.

### Roadmap: Pre-Merge

1. Remove `SetupShop` usage in `setup.py`
1. Use copy-pasteable GH Action for generation of standardized setup/requirements 
 	+ Source of Truth TBD: `requirements.txt`/`setup.py`/`setup.cfg`/etc.
1. Turn on the PyPI-publishing trigger within `semantic_release`'s GH Action

### Roadmap: Post-Merge
Proceed to update WIPAC repos in descending order of complexity. All updates:
- follow backward compatibility, unless there's a good reason not to
- publish to PyPI only what is needed by a client, if any
	+ prefix all PyPI packages with `wipac-`
- can be updated in time, there is no immediate necessary rush

Updates, in order:
1. Add [**wipac-telemetry**](https://github.com/WIPACrepo/wipac-telemetry-prototype) to PyPI _(PR TBA)_
	+ call it `wipac-telemetry` w/ `v1.0.0` (no longer prototype)
	+ has requirements, and requires `wipac-dev-tools` (and no other wipac packages)
	+ follow `Roadmap: Pre-Merge` workflow for this repo 
1. Add [**rest-tools**](https://github.com/WIPACrepo/rest-tools) to PyPI _(PR TBA)_
	+ publish on PyPI as `wipac-rest-tools`
	+ requires `wipac-telemetry` (and `wipac-dev-tools` in turn, but no other wipac packages)
		- TBD: Will this be an optional/extra pip feature: `wipac-rest-tools[wipac-telemetry]`?
			- Is tracing "core" to `rest-tools`? No. 
			- But is it worth separating the functionality at the package level? Maybe.
	+ follow `Roadmap: Pre-Merge` workflow for this repo
1. Add other utility repos to PyPI
	+ **MQClient** (+ child repos), **File Catalog** (required by FC Indexer), **KRS**
	+ fix requirements
	+ publish on PyPI with `wipac-` prefixes
	+ if/where PyPI is not appropriate for entire repo, then spinning-off utility repos may be wanted 
			- Ex: `wipac-file-catalog-types`, `wipac-krs-utils`
	+ follow `Roadmap: Pre-Merge` workflow for each repo
3. Fix requirements for each end-stream app
	+ **MOU Dash**, **Skymap Scanner**, **LTA**, **IceProd**
	+ these apps are not required by any "downstream" repo/client (not-published on PyPI)
	+ pre-merge: there may be some overlap with section above, see `"spinning-off utility repos"` point above
5. Fix requirements for each script
	+ **FC Indexer**, ...
	+ these are not required by any "downstream" repo/client (not-published on PyPI)

**Comment by dsschult** [comment]
If you want to save some duplication efforts, you could use the tool [cog](https://nedbatchelder.com/code/cog) along with a github action to render text into files programmatically.

An example of someone using `cog` to edit their build files:
https://github.com/hynek/structlog/commit/5e6ea9c04e070f7ef0106ff1256c58ef54c03686

**Comment by ric-evans** [comment]
> If you want to save some duplication efforts, you could use the tool [cog](https://nedbatchelder.com/code/cog) along with a github action to render text into files programmatically.
> 
> An example of someone using `cog` to edit their build files: [hynek/structlog@5e6ea9c](https://github.com/hynek/structlog/commit/5e6ea9c04e070f7ef0106ff1256c58ef54c03686)

I'm looking into https://github.com/jazzband/pip-tools
